# Versiones de Backend
# 1.1.1 Versión con la implementacion de versiones de la aplicación
# 1.1.2 Versión con la implementacion de AWS
# 1.1.3 Versión con la implementacion de CORS
# 1.1.4 Versión con ajustes de incidentes identificados en Portal Adminsitración
# 1.1.5 Versión con funcionalidades de ventas y movimientos
# 1.1.5 Ajustes en aliados mas usuados se le relacionaron los productos del punto de venta
version=1.1.5

